//! `violeet install-statusline` — the wrapper around whatever the user has.
//!
//! # Why violeet needs a status line at all
//!
//! Two numbers exist nowhere else. Claude Code passes them to the status line
//! command on stdin and to nothing else:
//!
//!  - `context_window.context_window_size` — the real window for this model
//!    **and this account**. Measured: the same `claude-opus-5` runs at 1M for
//!    one account and 200k for another, so it cannot be looked up from the
//!    model name. A table that tried showed 24% where the truth was 5%.
//!  - `rate_limits.five_hour` / `.seven_day` — the subscription's usage.
//!
//! # Why it is a wrapper and not a replacement
//!
//! The status line is the most visible thing in the agent's UI, and users have
//! one they built and care about. Replacing it to read a number off the payload
//! would be taking their prompt away to gather telemetry — a terrible trade,
//! and one they would notice immediately and blame on violeet.
//!
//! So the installed command **forwards the payload to the daemon and then runs
//! the original, printing its output verbatim**. On screen nothing changes.
//! That is the same absorb-rather-than-evict posture `install-hooks` takes with
//! a competing `PermissionRequest` hook, for the same reason.
//!
//! # Why the forward is fire-and-forget
//!
//! The status line renders on every frame of the agent's UI. A synchronous POST
//! there is felt directly as a laggy prompt, so the `curl` is backgrounded and
//! its failure is ignored: a daemon that is down must cost telemetry, never the
//! user's status line. The wrapper is also written to survive `curl` being
//! absent entirely.

use std::path::PathBuf;

use serde_json::Value;

use crate::settings::Settings;

/// Where the generated wrapper lives. Beside the socket, not in the user's
/// bin directory — it is violeet's own file and should be removable with the
/// rest of violeet's state.
pub fn wrapper_path() -> Option<PathBuf> {
    crate::probe::violeet_dir().map(|d| d.join("statusline-wrapper.sh"))
}

/// Where the original command is parked so `uninstall-statusline` can restore
/// it, and so the wrapper itself can find it.
pub fn parked_path() -> Option<PathBuf> {
    crate::probe::violeet_dir().map(|d| d.join("statusline-original.json"))
}

/// What is currently configured, if anything.
pub fn current(settings: &Settings) -> Option<Value> {
    settings.value.get("statusLine").cloned()
}

/// True if the configured status line is already ours.
pub fn is_ours(settings: &Settings) -> bool {
    current(settings)
        .and_then(|v| v.get("command").and_then(Value::as_str).map(str::to_string))
        .is_some_and(|c| c.contains("statusline-wrapper.sh"))
}

/// The wrapper script.
///
/// Deliberately plain `sh`. It runs on every status line render, so it must
/// start fast and must not depend on the user's shell configuration.
pub fn wrapper_script(port: u16, original: Option<&str>) -> String {
    let forward = format!(
        "printf '%s' \"$payload\" | curl -s -m 2 -X POST \
         'http://127.0.0.1:{port}/statusline' \
         -H 'content-type: application/json' --data-binary @- >/dev/null 2>&1 &"
    );

    let run_original = match original {
        // The original gets the payload on stdin exactly as Claude Code sent
        // it, so it cannot tell it has been wrapped.
        Some(command) => format!("printf '%s' \"$payload\" | {command}\n"),
        // No original: print nothing. An empty status line is what the user
        // had before, and inventing one would be violeet putting itself in a
        // place it was not asked to be.
        None => String::new(),
    };

    format!(
        "#!/bin/sh\n\
         # Generated by `violeet install-statusline`. Do not edit — it is\n\
         # rewritten on reinstall and removed by `violeet uninstall-statusline`.\n\
         #\n\
         # Reads the status line payload, forwards a copy to the violeet daemon,\n\
         # and then runs whatever status line was configured before, printing\n\
         # its output unchanged. On screen nothing about this is visible.\n\
         #\n\
         # The forward is backgrounded and its failure ignored on purpose: this\n\
         # runs on every frame of the agent's UI, so a daemon that is down must\n\
         # cost telemetry and never the user's prompt.\n\
         payload=$(cat)\n\
         \n\
         if command -v curl >/dev/null 2>&1; then\n\
         \x20 {forward}\n\
         fi\n\
         \n\
         {run_original}"
    )
}

/// The `statusLine` block that points at our wrapper.
pub fn wrapper_entry(path: &str) -> Value {
    serde_json::json!({
        "type": "command",
        "command": path,
    })
}

/// Pull the command string out of a `statusLine` entry.
pub fn command_of(entry: &Value) -> Option<String> {
    entry
        .get("command")
        .and_then(Value::as_str)
        .filter(|c| !c.is_empty())
        .map(str::to_string)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_wrapper_runs_the_original_with_the_untouched_payload() {
        let script = wrapper_script(9847, Some("$HOME/.claude/bin/ccstatusline"));

        assert!(script.contains("payload=$(cat)"));
        assert!(
            script.contains("printf '%s' \"$payload\" | $HOME/.claude/bin/ccstatusline"),
            "the original must receive the payload exactly as Claude Code sent it"
        );
    }

    /// The forward must not be able to slow the prompt down.
    #[test]
    fn the_forward_is_backgrounded_and_its_failure_ignored() {
        let script = wrapper_script(9847, Some("mystatus"));
        // The POST line, not the `command -v curl` guard above it.
        let forward_line = script
            .lines()
            .find(|l| l.contains("/statusline"))
            .expect("a forwarding line");

        assert!(forward_line.trim_end().ends_with('&'), "must be backgrounded");
        assert!(forward_line.contains("-m 2"), "and bounded");
        assert!(forward_line.contains(">/dev/null 2>&1"), "and silent");
    }

    /// A machine without curl must still get its status line.
    #[test]
    fn a_missing_curl_costs_telemetry_and_not_the_prompt() {
        let script = wrapper_script(9847, Some("mystatus"));
        assert!(script.contains("command -v curl"));

        let original_line = script.lines().position(|l| l.contains("mystatus"));
        let guard_line = script.lines().position(|l| l.contains("command -v curl"));
        assert!(
            original_line > guard_line,
            "the original runs after the guard, so it runs either way"
        );
    }

    /// No previous status line means we print nothing, rather than inventing
    /// one the user never asked for.
    #[test]
    fn with_no_original_the_wrapper_prints_nothing() {
        let script = wrapper_script(9847, None);
        assert!(script.contains("curl"));
        assert!(!script.contains("printf '%s' \"$payload\" | \n"));
        // The only printf is the forward.
        assert_eq!(script.matches("printf").count(), 1);
    }

    #[test]
    fn ours_is_recognized_by_the_wrapper_filename() {
        let entry = wrapper_entry("/Users/you/.violeet/statusline-wrapper.sh");
        assert_eq!(
            command_of(&entry).as_deref(),
            Some("/Users/you/.violeet/statusline-wrapper.sh")
        );
    }
}
