// swift-tools-version: 5.9
//
// This manifest exists so the app sources resolve and build from the command
// line (and so SwiftPM owns the SwiftTerm dependency in one place). The shipped
// macOS .app bundle is built from the Xcode project generated by XcodeGen out of
// project.yml — see the README.

import PackageDescription

let package = Package(
    name: "AITerm",
    platforms: [.macOS(.v14)],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftTerm", from: "1.15.0")
    ],
    targets: [
        .executableTarget(
            name: "AITerm",
            dependencies: [
                .product(name: "SwiftTerm", package: "SwiftTerm")
            ],
            path: "Sources/AITerm",
            // Info.plist is consumed by the Xcode target, not by SwiftPM; the
            // per-directory READMEs are orientation for humans, not resources.
            exclude: [
                "Info.plist",
                "Terminal/README.md",
                "Sidebar/README.md",
                "Daemon/README.md",
            ]
        )
    ]
)
